#!/usr/bin/python

import Tkinter, tkFileDialog, tkSimpleDialog
from libmassresize import massresize

root = Tkinter.Tk()
dirname = tkFileDialog.askdirectory(parent=root, title='Please select a directory')
width = tkSimpleDialog.askinteger(root, "Please select width of new images")
massresize(dirname, width)